DROP TABLE IF EXISTS EMPLOYEE;

CREATE SEQUENCE "EMPLOYEE_SEQ"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 100
NOCACHE
NOCYCLE;

CREATE TABLE EMPLOYEE (
  id INT default nextval('EMPLOYEE_SEQ') PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);
